spring:
  datasource:
    username: root
    password: 398936
    url: jdbc:mysql://10.3.4.65:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

jpa:
    show-sql: true
    hibernate:
        ddl-auto: update


